version: '3.9'

services:
  go:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    #volumes:
    #  - './src:/usr/local/bin/go-chatbot:rw'